name: Release unstoppabledefi-app-draft

on:
  push:
    branches: [ release ]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: IPFS Pinata deploy GitHub action
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: 'unstoppabledefi-app-draft'
          path: './src'
          pinata-api-key: ${{ secrets.PINATA_API_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_API_SECRET_KEY }}
          verbose: false
          remove-old: true

      - name: Pin to Crust
        uses: crustio/ipfs-crust-action@v1.0.8
        continue-on-error: true
        timeout-minutes: 2
        with:
          cid: ${{ steps.upload.outputs.hash }}
          seeds: ${{ secrets.CRUST_SEEDS }}
